Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # =====================
  # SERVER (Controller)
  # =====================
  config.vm.define "moouahab_S" do |server|
    server.vm.hostname = "moouahabS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/common.sh"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # =====================
  # WORKER (Agent)
  # =====================
  config.vm.define "moouahab_SW" do |worker|
    worker.vm.hostname = "moouahabSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/common.sh"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
